var tpj=jQuery;               // MAKE JQUERY PLUGIN CONFLICTFREE
tpj.noConflict();

tpj(document).ready(function() {
    tpj('#headerSection').parallax('50%', .60);
});

var $button2015 = tpj('#2015');
var $button2016 = tpj('#2016');
var $meetingPageInfo = tpj('#meetingPageInfo');


var info2016="";
info2016 += "				<div class=\"mtgInfoDiv\">";
info2016 += "					";
info2016 += "					<div class=\"mtgDate\"><h1>May 5-6, 2016<\/h1><\/div>";
info2016 += "";
info2016 += "					<div class=\"mtgLocation\">";
info2016 += "						<div>Google - New York<\/div>";
info2016 += "						<div>76 9th Avenue<\/div>";
info2016 += "						<div>New York, NY, 10011<\/div>";
info2016 += "					<\/div>";
info2016 += "					";
info2016 += "					<div>";
info2016 += "						<div class=\"mtgOverviewText\">The Economic and Statistics Administration (ESA) is giving notice of the fourth meeting of the Commerce Data Advisory Council (CDAC). The CDAC will discuss economic data as well as other Council matters. The CDAC will meet in a plenary session on May 5th and 6th, 2016. Last-minute changes to the schedule are possible, which could prevent giving advance public notice of schedule adjustments.  Members of the public are invited to observe the Committee proceedings and make comment during the public Comment session. Please see the <a href=\"https:\/\/www.federalregister.gov\/articles\/2016\/03\/10\/2016-05314\/commerce-data-advisory-council-meeting\">Federal Register Notice<\/a> for entry requirements and more information about the public comments.<\/div>";
info2016 += "					<\/div>";
info2016 += "					";
info2016 += "					<div class=\"row\">";
info2016 += "					<div class=\"mtgLinks col-md-4 col-md-offset-4\">";
info2016 += "							<p><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/november-2015\/cdac-charter-november-2015.pdf\">CDAC Charter<\/a><\/p>";
info2016 += "							<p><a href=\"#\">Meeting Agenda<\/a><\/p>";
info2016 += "							<p><a href=\"https:\/\/www.federalregister.gov\/articles\/2016\/03\/10\/2016-05314\/commerce-data-advisory-council-meeting\">Federal Register Notice<\/a><\/p>	";
info2016 += "					<\/div>";
info2016 += "					<\/div>";
info2016 += "";
info2016 += "					<div class=\"row\">";
info2016 += "						<div class=\"mtgVideo col-md-4 col-md-offset-4\">";
info2016 += "								<p><a href=\"#\">Day One Video<\/a><\/p>";
info2016 += "								<p><a href=\"#\">Day Two Video<\/a><\/p>";
info2016 += "						<\/div>";
info2016 += "					<\/div>";
info2016 += "";
info2016 += "					<div class=\"row presDiv\">";
info2016 += "						";
info2016 += "							<div class=\"mtgPresD1 col-md-6\">";
info2016 += "								<h4>Presentations - May 5, 2016<\/h4>";
info2016 += "								<table class=\"tablePresD1\">";
info2016 += "									<tr>";
info2016 += "										<th><p>Coming Soon!<\/p><\/th>";
info2016 += "									<\/tr>";
info2016 += "								<\/table>";
info2016 += "							<\/div>";
info2016 += "";
info2016 += "							<div class=\"mtgPresD2 col-md-5\">";
info2016 += "								<h4>Presentations - May 6, 2016<\/h4>						";
info2016 += "								<table class=\"tablePresD2\">";
info2016 += "									<tr>";
info2016 += "										<th><p>Coming Soon!<\/p><\/th>";
info2016 += "									<\/tr>";
info2016 += "								<\/table>";
info2016 += "							<\/div>";
info2016 += "						";
info2016 += "					<\/div>";
info2016 += "";
info2016 += "					<hr>";
info2016 += "				<\/div>";
info2016 += "";
info2016 += "";
info2016 += "";
info2016 += "				<div class=\"mtgInfoDiv\">";
info2016 += "					";
info2016 += "					<div class=\"mtgDate\"><h1>January 14, 2016<\/h1><\/div>";
info2016 += "";
info2016 += "					<div class=\"mtgLocation\">";
info2016 += "						<div>Virtual Meeting<\/div>";
info2016 += "					<\/div>";
info2016 += "					";
info2016 += "					<div>";
info2016 += "						<div class=\"mtgOverviewText\">On Thursday, January 14, 2016, three Commerce Data Advisory Council (CDAC) Working Groups (WG): Data Governance, Data Usability, and New Exporter will hold a separate meetings, through virtual means, to discuss perspective WG matters. The purpose of each session is to discuss the scope and definition of the working group, and to outline potential deliverables over the next 6 months.<\/div>";
info2016 += "					<\/div>";
info2016 += "					";
info2016 += "					<div class=\"row\">";
info2016 += "					<div class=\"mtgLinks col-md-4 col-md-offset-4\">";
info2016 += "							<p><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/november-2015\/cdac-charter-november-2015.pdf\">CDAC Charter<\/a><\/p>";
info2016 += "							<p><a href=\"#\">Meeting Agenda<\/a><\/p>";
info2016 += "							<p><a href=\"https:\/\/www.gpo.gov\/fdsys\/pkg\/FR-2016-01-05\/pdf\/2015-33154.pdf\">Federal Register Notice<\/a><\/p>	";
info2016 += "					<\/div>";
info2016 += "					<\/div>";
info2016 += "";
info2016 += "					<div class=\"row\">";
info2016 += "						<div class=\"mtgVideo col-md-4 col-md-offset-4\">";
info2016 += "								<p><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/cdac-new-exports-working-group-charter.pdf\">CDAC Working Group - New Exports<\/a><\/p>";
info2016 += "								<p><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/cdac-data-governance-working-group-charter.pdf\">CDAC Working Group - Data Governance<\/a><\/p>";
info2016 += "								<p><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/cdac-commerce-data-dashboard-working-group-charter.pdf\">CDAC Working Group - Data Dashboard<\/a><\/p>";
info2016 += "						<\/div>";
info2016 += "					<\/div>";
info2016 += "";
info2016 += "					<hr>";
info2016 += "				<\/div>";


var info2015="";
info2015 += "				<div class=\"mtgInfoDiv\">";
info2015 += "					";
info2015 += "					<div class=\"mtgDate\"><h1>October 29-30, 2015 <\/h1><\/div>";
info2015 += "";
info2015 += "					<div class=\"mtgLocation\">";
info2015 += "						<div>National Oceanic and Administration's<\/div>";
info2015 += "						<div>David Skaggs Research Center<\/div>";
info2015 += "						<div>325 Broadway<\/div>";
info2015 += "						<div>Boulder, CO 80305<\/div>";
info2015 += "					<\/div>";
info2015 += "					";
info2015 += "					<div>";
info2015 += "						<div class=\"mtgOverviewText\">The Economic and Statistics Administration (ESA) is giving notice of the Fall 2015 meeting of the Commerce Data Advisory Council (CDAC). The CDAC will discuss environmental data, workforce capabilities to improve data operations, data protection, and other Council matters. The CDAC will meet in a plenary session on October 29-30, 2015. Last-minute changes to the schedule are possible, which could prevent giving advance public notice of schedule adjustments. Members of the public are invited to observe the Committee proceedings and make comment during the public Comment session.  Please see the <a href=\"https:\/\/www.federalregister.gov\/articles\/2015\/09\/24\/2015-24334\/commerce-data-advisory-council-public-meeting\">Federal Register Notice<\/a> for entry requirements and more information about the public comments.<\/div>";
info2015 += "					<\/div>";
info2015 += "					";
info2015 += "					<div class=\"row\">";
info2015 += "					<div class=\"mtgLinks col-md-4 col-md-offset-4\">";
info2015 += "							<p><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/november-2015\/cdac-charter-november-2015.pdf\">CDAC Charter<\/a><\/p>";
info2015 += "							<p><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/november-2015\/cdac-agenda-october-2015.pdf\">Meeting Agenda<\/a><\/p>";
info2015 += "							<p><a href=\"https:\/\/www.federalregister.gov\/articles\/2015\/09\/24\/2015-24334\/commerce-data-advisory-council-public-meeting\">Federal Register Notice<\/a><\/p>	";
info2015 += "					<\/div>";
info2015 += "					<\/div>";
info2015 += "";
info2015 += "					<div class=\"row\">";
info2015 += "						<div class=\"mtgVideo col-md-4 col-md-offset-4\">";
info2015 += "								<p><a href=\"https:\/\/www.youtube.com\/watch?v=2pWaFbnAik4&feature=youtu.be\">Day One Video<\/a><\/p>";
info2015 += "								<p><a href=\"https:\/\/www.youtube.com\/watch?v=vvYa0Ta_nzc&feature=youtu.be\">Day Two Video<\/a><\/p>";
info2015 += "						<\/div>";
info2015 += "					<\/div>";
info2015 += "";
info2015 += "					<div class=\"row presDiv\">";
info2015 += "						";
info2015 += "							<div class=\"mtgPresD1 col-md-6\">";
info2015 += "								<h4>Presentations - NOAA<\/h4>";
info2015 += "								<table class=\"tablePresD1\">";
info2015 += "									<tr>";
info2015 += "										<th><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/november-2015\/cdac-presentation-key-challenges-for-environmental-data-and-information-as-viewed-from-ncei-tom-karl.pdf\"><p>Getting Data To Our Customers<\/p><\/a><\/th>";
info2015 += "										<th><p>Tom Karl, NOAA<\/p><\/th>";
info2015 += "									<\/tr>";
info2015 += "									<tr>";
info2015 += "										<th><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/november-2015\/cdac-presentation-noaa-big-data-project.pdf\"><p>NOAA Big Data Proejct<\/p><\/a><\/th>";
info2015 += "										<th><p>Brian Eiler, NOAA<\/p><\/th>";
info2015 += "									<\/tr>";
info2015 += "									<tr>";
info2015 += "										<th><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/november-2015\/cdac-presentation-lessons-for-cdac-from-noaa-data-policies-bill-gail.pdf\"><p>Lessons for CDAC from NOAA Data Policies<\/p><\/a><\/th>";
info2015 += "										<th><p>Bill Gail, Global Weather Corporation<\/p><\/th>";
info2015 += "									<\/tr>";
info2015 += "								<\/table>";
info2015 += "							<\/div>";
info2015 += "";
info2015 += "							<div class=\"mtgPresD2 col-md-5\">";
info2015 += "								<h4>Presentations - CDAC Members and Cybersecurity<\/h4>						";
info2015 += "								<table class=\"tablePresD2\">";
info2015 += "									<tr>";
info2015 += "										<th><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/november-2015\/cdac-presentation-converting-data-into-actionable-insights-borner.pdf\"><p>Converting Data in Action<\/p><\/a><\/th>";
info2015 += "										<th><p>Katy Borner, Indiana University<\/p><\/th>";
info2015 += "									<\/tr>";
info2015 += "									<tr>";
info2015 += "										<th><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/november-2015\/cdac-presentation-discovery-and-use-of-commerce-data-from-a-small-business-perspective.pdf\"><p>Discovery and Use of Commerce Data from Small Businesses<\/p><\/a><\/th>";
info2015 += "										<th><p>Karin Remington, Arjuna Solutions<\/p><\/th>";
info2015 += "									<\/tr>";
info2015 += "									<tr>";
info2015 += "										<th><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/november-2015\/cdac-presentation-strengthening-americas-data-agency.pdf\"><p>Commerce Update and Response to CDAC Recommendations<\/p><\/a><\/th>";
info2015 += "										<th><p>Ian Kalin, DCO<\/p><\/th>";
info2015 += "									<\/tr>";
info2015 += "									<tr>";
info2015 += "										<th colspan=\"2\">";
info2015 += "											<ul>";
info2015 += "												<li>Related Presentation: <a href=\"http:\/\/www.esa.doc.gov\/reports\/fostering-innovation-creating-jobs-driving-better-decisions-value-government-data\">Fostering Innovation<\/a><\/li>";
info2015 += "												<li>Related Presentation: <a href=\"https:\/\/www.commerce.gov\/sites\/commerce.gov\/files\/media\/files\/2014\/doc_fy2014-2018_strategic_plan.pdf\">America Is Open for Business<\/a><\/li>";
info2015 += "											<\/ul>";
info2015 += "										<\/th>";
info2015 += "									<\/tr>";
info2015 += "									<tr>";
info2015 += "										<th><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/november-2015\/cdac-presentation-the-computer-security-division-nist.pdf\">NIST Cybersecurity Reference Materials<\/a><\/th>";
info2015 += "										<th><p>Matthew Schnoll, NIST<\/p><\/th>";
info2015 += "									<\/tr>";
info2015 += "								<\/table>";
info2015 += "							<\/div>";
info2015 += "						<\/div>";
info2015 += "					<hr>";
info2015 += "				<\/div>";
info2015 += "";
info2015 += "				<div class=\"mtgInfoDiv\">";
info2015 += "					";
info2015 += "					<div class=\"mtgDate\"><h1>July 30, 2015 <\/h1><\/div>";
info2015 += "";
info2015 += "					<div class=\"mtgLocation\">";
info2015 += "						<div>Intel Corporation, Robert Noyce Building<\/div>";
info2015 += "						<div>2200 Mission College Blvd.<\/div>";
info2015 += "						<div>Santa Clara, CA 95054<\/div>";
info2015 += "					<\/div>";
info2015 += "					";
info2015 += "					<div>";
info2015 += "						<div class=\"mtgOverviewText\">The second meeting of the Commerce Data Advisory Council. Members of the public were invited on a first come, first served basis (depending on the availability of meeting room space) to listen to the Committee proceedings and to make comments.<\/div>";
info2015 += "					<\/div>";
info2015 += "					";
info2015 += "					<div class=\"row\">";
info2015 += "					<div class=\"mtgLinks col-md-4 col-md-offset-4\">";
info2015 += "							<p><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/cdac-april-2015--charter.pdf\">CDAC Charter<\/a><\/p>";
info2015 += "							<p><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/july-2015\/cdac-agenda-july-2015.pdf\">Meeting Agenda<\/a><\/p>";
info2015 += "							<p><a href=\"https:\/\/www.federalregister.gov\/articles\/2015\/06\/16\/2015-14796\/commerce-data-advisory-council\">Federal Register Notice<\/a><\/p>	";
info2015 += "					<\/div>";
info2015 += "					<\/div>";
info2015 += "";
info2015 += "					<div class=\"row\">";
info2015 += "						<div class=\"mtgVideo col-md-4 col-md-offset-4\">";
info2015 += "								<p><a href=\"https:\/\/www.youtube.com\/watch?v=qEfjueCqyDQ\">Day One Video<\/a><\/p>";
info2015 += "								<p><a href=\"https:\/\/www.youtube.com\/watch?v=mhEsIiKy0ok\">Day Two Video<\/a><\/p>";
info2015 += "						<\/div>";
info2015 += "					<\/div>";
info2015 += "";
info2015 += "					<div class=\"row presDiv\">";
info2015 += "						";
info2015 += "							<div class=\"mtgPresD1 col-md-6\">";
info2015 += "								<h4>Presentations - Income, Patent, and Trademark Data<\/h4>";
info2015 += "								<table class=\"tablePresD1\">";
info2015 += "									<tr>";
info2015 += "										<th><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/july-2015\/cdac-july-2015-presentation-census-economic-inequality.pdf\"><p>Income Data<\/p><\/a><\/th>";
info2015 += "										<th><p>Enrique Lamas, Trudi Renwick, US Census Bureau<\/p><\/th>";
info2015 += "									<\/tr>";
info2015 += "									<tr>";
info2015 += "										<th><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/july-2015\/cdac-july-2015-presentation-census-commerce-income-project.pdf\"><p>Commerce Income Data Project<\/p><\/a><\/th>";
info2015 += "										<th><p>Lisa Wolfisch, US Census Bureau<\/p><\/th>";
info2015 += "									<\/tr>";
info2015 += "									<tr>";
info2015 += "										<th><p>Income Site MockUp<\/p><\/th>";
info2015 += "										<th><p>Lisa Wolfisch, US Census Bureau<\/p><\/th>";
info2015 += "									<\/tr>";
info2015 += "									<tr>";
info2015 += "										<th><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/july-2015\/cdac-july-2015-presentation-pto-open-data-roadmap.pdf\"><p>Open Data RoadMap<\/p><\/a><\/th>";
info2015 += "										<th>Thomas Beach, USPTO<\/th>";
info2015 += "									<\/tr>";
info2015 += "								<\/table>";
info2015 += "							<\/div>";
info2015 += "";
info2015 += "							<div class=\"mtgPresD2 col-md-5\">";
info2015 += "								<h4>Presentations - Workforce and Skills, Public Partnerships & Feedback<\/h4>						";
info2015 += "								<table class=\"tablePresD2\">";
info2015 += "									<tr>";
info2015 += "										<th><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/july-2015\/cdac-july-2015-presentation-18f-government-digital-commercial-corps.pdf\"><p>18F: Government Digital Commercial Corps<\/p><\/a><\/th>";
info2015 += "										<th><p>Hillary Hartley, 18F, GSA<\/p><\/th>";
info2015 += "									<\/tr>";
info2015 += "									<tr>";
info2015 += "										<th><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/july-2015\/cdac-july-2015-presentation-census-filling-hard-to-acquire-talent.pdf\"><p>Filling Hard to Acquire Talent<\/p><\/a><\/th>";
info2015 += "										<th><p>John Thompson, Director, US Census Bureau<\/p><\/th>";
info2015 += "									<\/tr>";
info2015 += "									<tr>";
info2015 += "										<th><p>Commercial Data Service Launch<\/p><\/th>";
info2015 += "										<th><p>Ian Kalin, DOC<\/p><\/th>";
info2015 += "									<\/tr>";
info2015 += "									<tr>";
info2015 += "										<th><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/july-2015\/cdac-july-2015-presentation-doc-digital-economy.pdf\">Digital Economy<\/a><\/th>";
info2015 += "										<th><p>Department of Commerce<\/p><\/th>";
info2015 += "									<\/tr>";
info2015 += "								<\/table>";
info2015 += "							<\/div>";
info2015 += "						<\/div>";
info2015 += "					<hr>";
info2015 += "				<\/div>";
info2015 += "";
info2015 += "				<div class=\"mtgInfoDiv\">";
info2015 += "					";
info2015 += "					<div class=\"mtgDate\"><h1>April 23-24, 2015 <\/h1><\/div>";
info2015 += "";
info2015 += "					<div class=\"mtgLocation\">";
info2015 += "						<div>Google Washington, DC<\/div>";
info2015 += "						<div>25 Massachusetts Ave. NW<\/div>";
info2015 += "						<div>Suite 900<\/div>";
info2015 += "						<div>Washington, DC 20001<\/div>";
info2015 += "					<\/div>";
info2015 += "					";
info2015 += "					<div>";
info2015 += "						<div class=\"mtgOverviewText\">The inaugural meeting of the Commerce Data Advisory Council was held on Thursday, April 23 and Friday, April 24, 2015 at Google Washington, DC, 25 Massachusetts Avenue NW, Suite 900, Washington, DC 20001. Members of the public were invited on a first come, first served basis (depending on the availability of meeting room space) to listen to the Committee proceedings and to make comments.<\/div>";
info2015 += "					<\/div>";
info2015 += "					";
info2015 += "					<div class=\"row\">";
info2015 += "					<div class=\"mtgLinks col-md-4 col-md-offset-4\">";
info2015 += "							<p><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/commerce-data-advisory-council-agenda-april-2015.pdf\">Meeting Agenda<\/a><\/p>";
info2015 += "							<p><a href=\"http:\/\/www.esa.doc.gov\/content\/upcoming-past-meetings#\">Federal Register Notice<\/a><\/p>	";
info2015 += "					<\/div>";
info2015 += "					<\/div>";
info2015 += "";
info2015 += "					<div class=\"row\">";
info2015 += "						<div class=\"mtgVideo col-md-4 col-md-offset-4\">";
info2015 += "								<p><a href=\"https:\/\/www.youtube.com\/watch?v=vaPIYb7NDRc\">Meeting Footage<\/a><\/p>";
info2015 += "						<\/div>";
info2015 += "					<\/div>";
info2015 += "";
info2015 += "					<div class=\"row presDiv\">";
info2015 += "						";
info2015 += "							<div class=\"mtgPresD1 col-md-6\">";
info2015 += "								<h4>Presentations - April 23, 2015<\/h4>";
info2015 += "								<table class=\"tablePresD1\">";
info2015 += "									<tr>";
info2015 += "										<th><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/ignite-cdac-census.ppsx\"><p>U.S. Census Bureau<\/p><\/a><\/th>";
info2015 += "										<th><p>Jeannie Shiffer, US Census Bureau<\/p><\/th>";
info2015 += "									<\/tr>";
info2015 += "									<tr>";
info2015 += "										<th><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/ignite-cdac-noaa.pptx\"><p>CThe NOAA Big Data Project<\/p><\/a><\/th>";
info2015 += "										<th><p>Brian Eiler, NOAA<\/p><\/th>";
info2015 += "									<\/tr>";
info2015 += "									<tr>";
info2015 += "										<th><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/ignite-cdac-pto-real.pdf\"><p>Celebrating 225 Years of Open Data<\/p><\/a><\/th>";
info2015 += "										<th><p>Ajay Kundaria, Patent & Trademark Office<\/p><\/th>";
info2015 += "									<\/tr>";
info2015 += "									<tr>";
info2015 += "										<th><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/ignite-cdac-ntis.pdf\"><p>Decrypting Data: myUSCIS<\/p><\/a><\/th>";
info2015 += "										<th>Michelle Williams, National Technical & Information Services Bureau<\/th>";
info2015 += "									<\/tr>";
info2015 += "									<tr>";
info2015 += "										<th><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/ignite-presentation-bea-lucas-hitt.pdf\"><p>A Legacy of Data & A Future of Opportunity<\/p><\/a><\/th>";
info2015 += "										<th>Lucas Hitt, Bureau of Economic Analysis<\/th>";
info2015 += "									<\/tr>";
info2015 += "									<tr>";
info2015 += "										<th><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/ignite-cdac-ita.pdf\"><p>International Trade Administration Trade Developer Portal<\/p><\/a><\/th>";
info2015 += "										<th>Kim Becht & Stuart Ridgway, ITA<\/th>";
info2015 += "									<\/tr>";
info2015 += "								<\/table>";
info2015 += "							<\/div>";
info2015 += "";
info2015 += "							<div class=\"mtgPresD2 col-md-5\">";
info2015 += "								<h4>Presentations - April 24, 2015<\/h4>						";
info2015 += "								<table class=\"tablePresD2\">";
info2015 += "									<tr>";
info2015 += "										<th><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/cdo-goals.pdf\"><p>Open Data 2.0: Overview of the Commerce Department's Data Plan<\/p><\/a><\/th>";
info2015 += "										<th><p>Ian Kalin, DOC and Lynn Overmann, DOC<\/p><\/th>";
info2015 += "									<\/tr>";
info2015 += "									<tr>";
info2015 += "										<th><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/cdac--member-presentations-zillow.pdf\"><p>Zillow's Use of Public Data<\/p><\/a><\/th>";
info2015 += "										<th><p>Stan Humphries, Zillow<\/p><\/th>";
info2015 += "									<\/tr>";
info2015 += "									<tr>";
info2015 += "										<th><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/cdac-member-presentations-gwc.pptx\"><p>Lessons for CDAC from Environmental Data<\/p><\/a><\/th>";
info2015 += "										<th><p>William Gail, Global Weather Corporation<\/p><\/th>";
info2015 += "									<\/tr>";
info2015 += "									<tr>";
info2015 += "										<th><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/cdac-presentation-kevin-merritt-socrata.pdf\"><p>DATA: Government's Most Valuable Renewable Resource<\/p><\/a><\/th>";
info2015 += "										<th><p>Kevin Merritt, Socrata<\/p><\/th>";
info2015 += "									<\/tr>";
info2015 += "									<tr>";
info2015 += "										<th><a href=\"http:\/\/www.esa.doc.gov\/sites\/default\/files\/cdac\/cdac-member-presentations-datainnovation.pptx\"><p>Open Data in the G8<\/p><\/a><\/th>";
info2015 += "										<th><p>Daniel Castro, Center for Data Innovation<\/p><\/th>";
info2015 += "									<\/tr>";
info2015 += "								<\/table>";
info2015 += "							<\/div>";
info2015 += "						<\/div>";
info2015 += "					<hr>";
info2015 += "				<\/div>";




$button2015.click( function(e) {
    e.preventDefault();
    $meetingPageInfo.html(info2015);
});

$button2016.click( function(e) {
    e.preventDefault();
    $meetingPageInfo.html(info2016);
})
